version: '3.8'

services:
  backend:
    container_name: backend.dailyplanify
    image: shinsenter/symfony:php8.3-alpine
    ports:
      - "8000:80"
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: ${DATABASE_NAME:-dailyplanify}
      DATABASE_USER: ${DATABASE_USER:-dailyplanify}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-dailyplanifypassword}
    networks:
      - database
    volumes:
      - ./BackEnd:/var/www/html

  database:
    container_name: database.dailyplanify
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME:-dailyplanify}
      MYSQL_USER: ${DATABASE_USER:-dailyplanify}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-dailyplanifypassword}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-dailyplanifypassword}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    networks:
      - database
    volumes:
      - ./volumes/dailyplanify/database/data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin.dailyplanify
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"  # PHPMyAdmin will be accessible at http://localhost:8090
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-dailyplanifypassword}
    networks:
      - database

  frontend:
    container_name: frontend.dailyplanify
    image: node:latest
    working_dir: /app
    volumes:
      - ./FrontEnd:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - database

networks:
  database: {}

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
